# Generated by Django 3.2.5 on 2022-02-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thermo', models.FloatField(max_length=20)),
                ('heartrate', models.IntegerField(max_length=20)),
                ('time', models.DateTimeField(max_length=20)),
            ],
        ),
    ]
