# Generated by Django 3.2.5 on 2022-02-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonitoringApp', '0003_environment'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_humid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(max_length=20)),
                ('humid', models.FloatField(max_length=20)),
                ('time', models.DateTimeField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='environment',
            new_name='gas',
        ),
    ]
