# Generated by Django 3.2.5 on 2022-02-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonitoringApp', '0004_auto_20220228_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gas',
            name='CO_ppm',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='gas',
            name='LPG_ppm',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='gas',
            name='gas_voltage_level',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='health',
            name='thermo',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='temp_humid',
            name='humid',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='temp_humid',
            name='temp',
            field=models.FloatField(max_length=10),
        ),
    ]
